"""Markdown report writer - the human-readable artifact."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Dict, Any, List


def render(bundle: Dict[str, Any]) -> str:
    lines: list[str] = []
    s = bundle["subject_query"]
    meta = bundle["meta"]
    lines.append(f"# shadowtrace profile - {s}")
    lines.append("")
    lines.append(f"- Subject ID: `{meta['subject_id']}`")
    lines.append(f"- Run at: {meta['run_iso']}")
    lines.append(f"- Operator: {meta['operator']}")
    lines.append(f"- Consent tier: **{meta['consent']['tier']}**"
                 + (f" (EU-detected)" if meta['consent']['eu_subject'] else ""))
    lines.append(f"- Sources hit: {', '.join(sorted(meta['sources_hit']))}")
    lines.append(f"- Records: {meta['record_count']} | Clusters: {meta['cluster_count']}")
    lines.append("")

    prof = bundle["profile"]
    lines.append("## Behavioral synthesis")
    if prof.get("bio_excerpt"):
        lines.append("")
        lines.append("**Bio excerpt:**")
        lines.append("")
        lines.append("> " + prof["bio_excerpt"].replace("\n", "\n> "))
    lines.append("")
    if prof.get("top_titles"):
        lines.append("**Top titles:** " + ", ".join(f"{t} ({c})" for t, c in prof["top_titles"]))
    if prof.get("top_orgs"):
        lines.append("**Top orgs:** " + ", ".join(f"{o} ({c})" for o, c in prof["top_orgs"]))
    if prof.get("top_locations"):
        lines.append("**Locations:** " + ", ".join(f"{l} ({c})" for l, c in prof["top_locations"]))
    if prof.get("year_footprint"):
        yrs = prof["year_footprint"]
        lines.append(f"**Temporal footprint:** {yrs[0]} - {yrs[-1]} ({len(yrs)} distinct years)")
    lines.append(f"**Source breakdown:** {dict(prof['source_breakdown'])}")
    lines.append("")

    claims = bundle["corroborated_claims"][:12]
    lines.append("## Corroborated claims (top 12)")
    lines.append("")
    if not claims:
        lines.append("_None crossed the corroboration threshold._")
    for c in claims:
        star = " ✓" if c["corroborated"] else ""
        lines.append(f"- [{c['combined_confidence']}{star}] {c['claim']}  "
                     f"_(sources: {', '.join(c['sources'])})_")
    lines.append("")

    ns = bundle["negative_space"]
    lines.append("## Negative space (what's missing)")
    lines.append(f"- Guessed archetype: **{ns['guessed_archetype']}**")
    lines.append(f"- Expected signals for archetype: {', '.join(ns['expected_signals'])}")
    if ns["gaps"]:
        lines.append("- Gaps:")
        for g in ns["gaps"]:
            lines.append(f"  - {g}")
    else:
        lines.append("- No gaps detected - record set proportional.")
    lines.append(f"- Interpretation: {ns['interpretation']}")
    lines.append("")

    lines.append("## Adversarial checks")
    adv = bundle["adversarial"]
    for ch in adv["counter_hypotheses"][:6]:
        lines.append(f"- Claim: _{ch['claim'][:120]}_")
        for h in ch["hypotheses"]:
            lines.append(f"  - ? {h}")
    lines.append("")
    lines.append("## Red-team (what subject might prefer hidden)")
    for r in adv["red_team"]:
        lines.append(f"- {r}")
    lines.append("")

    guide = bundle["interaction_guide"]
    lines.append("## Engagement guide")
    if guide:
        for g in guide:
            lines.append(f"- {g}")
    else:
        lines.append("- Signal too sparse to recommend engagement strategy.")
    lines.append("")

    lines.append("## Provenance")
    for r in bundle["records"][:30]:
        u = f" <{r['url']}>" if r.get("url") else ""
        lines.append(f"- `{r['source']}` conf={r['confidence']:.2f} auth={r['authority']:.2f}{u}")
    if len(bundle["records"]) > 30:
        lines.append(f"- ... +{len(bundle['records']) - 30} more records in JSON export")
    lines.append("")

    lines.append("## Ethics note")
    lines.append(f"- Sole operator: {meta['operator']}")
    lines.append(f"- Consent tier: {meta['consent']['tier']}")
    lines.append(f"- Sensitive-category redaction: {meta['consent']['sensitive_redact']}")
    lines.append(f"- robots.txt compliant: {meta['robots_compliant']}")
    lines.append(f"- Audit log: `{meta['audit_log']}`")
    lines.append("")
    lines.append("_Generated by shadowtrace v7 — single-operator, public sources only, audit-logged._")
    return "\n".join(lines)


def write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
